import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import "./globals.css";
import Session from "./auth/Session";
import QueryClientProvider from "./QueryClientProvider";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <Session>
            <Theme accentColor="violet">
              <Navbar />
              <main className="px-8">
                <Container>
                  {children}
                  <Analytics />
                </Container>
              </main>
            </Theme>
          </Session>
        </QueryClientProvider>
      </body>
    </html>
  );
}
